### ISSUE TITLE
[view] Apply Brush Feature to TemporalFilter Component

### ISSUE THREAD

**Issue by jeonghye-choi** [githru/githru-vscode-ext#164]
## Description

릴리즈 일정을 위해 Temporal Filter의 구간 설정을 기간 설정(input date)으로 적용 했었음. 해당 부분을 Brush로 기간을 선택할 수 있도록 변경

## Task

- [ ] Brush 기능 구현
- [ ] Brush로 Line Chart 구간 선택에 따른 날짜 연결 기능
- [ ] 날짜에 따른 Filtering 기능 구현

**Comment by ytaek** [comment]
Brush는 시급하게 들어가야할 것 같습니다!
