### ISSUE TITLE
[view] Change Bar Chart to Line Chart in TemporalFilter Component

### ISSUE THREAD

**Issue by jeonghye-choi** [githru/githru-vscode-ext#166]
## Description

trend를 알고 싶다는 목적을 위해서 Bar chart를 Line Chart로 변경

- #145 의 '추후 수정 예정' 부분입니다

## Task

- [x] Bar Chart를 Line Chart로 변경
- [x] y축 오른쪽 배치 -> 왼쪽 배치 변경
- [x] x축 날짜 표시 조금 더 디테일 하게 변경
- [x] styles: 아랫쪽을 더 쳐다보도록 회색 계정 컬러 + 톤다운
- [ ] brushing 기능 추가에 따른 filtered in 된 부분에 main color 하이라이트 (dependency on #164)

**Comment by kmin-jeong** [comment]
- [ ] Bar Chart를 Line Chart로 변경
- [ ] y축 오른쪽 배치 -> 왼쪽 배치 변경
- [ ] x축 날짜 표시 조금 더 디테일 하게 변경
- [ ] styles: 아랫쪽을 더 쳐다보도록 회색 계정 컬러 + 톤다운
Temporal filter에서 이부분들 작업하겠습니다!

**Comment by ytaek** [comment]
Line chart변경도 빨리 들어가면 좋겠습니다.

**Comment by ytaek** [comment]
앗 기한님이 Bar Chart를 Line Chart로 변경을 급하게 해주시기로 하셨습니다.
일단 reopen 할께요!
