### ISSUE TITLE
[engine]git log parser test code 구현

### ISSUE THREAD

**Issue by kmin-jeong** [githru/githru-vscode-ext#28]
## Task 
- [ ] test code 세팅 --jest 이슈도 생각해보기
- [ ] json mock data 작성하기 (될수 있는한 다양한 사례로)
- [ ]  백슬레시도 문자열로 고려될수 있는지 찾아보기
```
export const exampleLog01 = `
commit df463687612482d66f0ed9d938aef279dba2a19c faea5b2adfb1376ef22f1cb45e9e827cd2618221
Author:     Josh Gross <joshmgross@github.com>
AuthorDate: Thu Jan 6 14:39:07 2022 -0500
Commit:     Josh Gross <joshmgross@github.com>
CommitDate: Thu Jan 6 14:39:07 2022 -0500

    Use \`jonabc/setup-licensed\` in Licensed workflow

6       6       .github/workflows/licensed.yml
`
```

**Comment by kmin-jeong** [comment]
task를 대략적으로 적었는데 부족한 점이 보인다면 피드백 환영합니다!
