### ISSUE TITLE
[engine] git log parse_commitList 구현

### ISSUE THREAD

**Issue by blcklamb** [githru/githru-vscode-ext#29]
## 구현 설명

[메인 이슈](https://github.com/githru/githru-vscode-ext/issues/22)
DAG으로 넘기기 위해 commitList를 return합니다.

## input과 output 참고
https://github.com/githru/githru-vscode-ext/issues/22#issuecomment-1221248982
https://github.com/githru/githru-vscode-ext/issues/22#issuecomment-1221302156

## Task

- [x] git log spawn 기능 구현
- [x] commitList Interface 구성
    - [x] PR 정보가 들어가는지는 추후 논의를 통해 결정 [참고](https://github.com/githru/githru-vscode-ext/issues/27)
- [x] git log parse 기능 구현
    - [x] `fileChanged`의 경우 @anpaul0615 님께서 작성하신 함수 참고하기

## 문의 사항
[폴더 구조](https://github.com/githru/githru-vscode-ext/discussions/10#discussioncomment-3437256)

**Comment by anpaul0615** [comment]
@blcklamb
fileChanged 파싱 참고용 코드 공유드려요!
(https://github.com/githru/githru-feature-practices/blob/main/parser/anpaul0615/src/domain/githru.ts#L51-L87)

input : 
```typescript
type numStat = string | undefined;
/* example : 
14      0       lib/page/todoey/model/task_data.dart
9       18      lib/page/todoey/screens/tasks_screen.dart
6       1       lib/page/todoey/todoey.dart
20      25      lib/page/todoey/widgets/tasks_list.dart
*/
```

output : 
```typescript
type diffStat = {
  changedFileCount: number;
  insertions: number;
  deletions: number;
  files: {
    [filename: string]: {
      insertions: number;
      deletions: number;
    };
  };
};
```

sample code : 
```javascript
    // ...

    if (props.numStat) {
      const numStats = props.numStat
        .split('\n')
        .map((r) => r.split('\t'))
        .map(([ins, dels, fileName]) => {
          return {
            ins: ins === '-' ? 0 : Number(ins),
            dels: dels === '-' ? 0 : Number(dels),
            fileName,
          };
        })
        .slice(0, -1);

      for (const { ins, dels, fileName } of numStats) {
        instance.diffStat.changedFileCount += 1;
        instance.diffStat.insertions += ins;
        instance.diffStat.deletions += dels;
        instance.diffStat.files[fileName] = {
          insertions: ins,
          deletions: dels,
        };
      };
    }
```
