### ISSUE TITLE
[view] Temporal Filter Line Chart 구간 필터 구현

### ISSUE THREAD

**Issue by jeonghye-choi** [githru/githru-vscode-ext#32]
## 구현 설명

<img width="264" alt="image" src="https://user-images.githubusercontent.com/54584063/185929271-5a768c8e-9521-43e6-a183-b13f1dcc2f5c.png">

## Task
- [x] 날짜에 따른 Filter
- [x] Filter된 데이터 전역 상태 반영
  - Vertical Cluster List, Statistics 컴포넌트에 반영될 수 있도록
- [ ] 테스트 코드 작성

**Comment by jin-Pro** [comment]
Temporal Filter LineChart 내부에서 구간 선택 기능 구현 예정도 있을까요?

**Comment by jeonghye-choi** [comment]
네! 드래그를 통한 구간 설정 기능도 추가할 예정입니다!
