### ISSUE TITLE
[view] Statistics - Author Bar chart 구현 (v0.1.0)

### ISSUE THREAD

**Issue by hanseul-lee** [githru/githru-vscode-ext#58]
## Description
<img width="300" alt="image" src="https://user-images.githubusercontent.com/69497936/187429559-9721ac56-fe0c-4c17-913f-191896457eeb.png"><img width="300" alt="image" src="https://user-images.githubusercontent.com/69497936/187433061-dcc38fd6-e64d-4772-a9e9-c4762b646f3e.gif" />

-  전체 혹은 선택된 기간 내 author 데이터에 대한 bar chart 구현
    - author 별 commit, total files changed, total insertions, total deletions 수치 및 순위
    - 기존 githru compare의 files의 chart 참고

## Task
- [x] 선택된 Cluster 데이터를 author 기준으로 받도록 가공
- [x] Bar chart 구현
- [x] metric 변경 시 인터렉션 구현

**Comment by hanseul-lee** [comment]
## 9/3 1차 구현

### WorkList
- 선택된 Cluster 데이터를 author 기준으로 받도록 가공
- Bar chart 구현
- metric 변경 시 인터렉션 구현

## Result
<img src="https://user-images.githubusercontent.com/69497936/188274438-817d5293-0d7b-4354-b3db-21acdfe9c611.gif" width="400" />


## After Todo
- [ ] 툴팁 추가
- [ ] focusText 추가
- [ ] 데이터 10개 초과 시 최대 10개만 렌더되도록 갯수 제한
- [ ] metric 변경 시 transition 추가
- [ ] 반응형 구현
- [ ] 엔진팀 실제 데이터와 연동

**Comment by hanseul-lee** [comment]
## 9/9 2차 구현

### Related PR
- #113

### WorkList
- metric 변경 시 transition 추가
- 툴팁 추가
- 데이터 10개 초과 시 최대 10개만 렌더되도록 갯수 제한
- author name y축 세부 위치 조정
- bar class 내 text와 rect 그룹화 및 hover 스타일 변경 적용
- scss 네이밍 수정 및 nesting 적용

## Result
<img src="https://user-images.githubusercontent.com/69497936/189365495-88106406-5a57-4980-a7fa-8af597915e44.gif" width="400" />

## After Todo
- [ ] 반응형 구현
- [ ] 엔진팀 실제 데이터와 연동
